#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width 1
bspc config window_gap 5
bspc config top_padding 5
bspc config bottom_padding 5
bspc config right_padding 5
bspc config left_padding 5

bspc config normal_border_color "#292929"
bspc config active_border_color "#292929"
bspc config focused_border_color "#333333"
bspc config presel_feedback_color "#292929"

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Brave-browser desktop='^1'
bspc rule -a qBittorrent desktop='^4'
bspc rule -a Pick-colour-picker state=floating
bspc rule -a org.wezfurlong.wezterm rectangle=670x400+370+170 state=pseudo_tiled
