picom --animations  &                  # compositor
xset r rate 300 50 &                   # repeated key rate
wal -R &                               # set wallpaper and colors
setxkbmap br -option caps:swapescape & # change esc by capslock
ibus-daemon -drxR &                    # input method
redshift &                             # screen color temperature
dunst &                                # notifications daemon
xsetroot -cursor_name left_ptr &       # set cursor type
unclutter &                            # hide mouse
qbittorrent &                          # torrent client
anki &                                 # srs flashcards

exec bspwm                             # window manager
