# barriers -a 192.168.2.2 --disable-crypto -l /tmp/barrier.log -c /home/ludwiklejzer/.config/barrier/barrier.conf &
picom  & # compositor
# dunst &
setxkbmap -option caps:swapescape & # change esc by capslock
redshift &                             # screen color temperature
xsetroot -cursor_name left_ptr &       # set cursor type
unclutter &                            # hide mouse
deluged &
# ping -c 1 192.168.2.3 &>/dev/null && sshfs ludwiklejzer@192.168.2.3:/home/ludwiklejzer e2220 &
# wezterm start nvim -c "exe 'VimwikiIndex' | bd | e ~/wiki/Goals.md" &

exec awesome                             # window manager
# exec bspwm
