picom --experimental-backends --animations & # compositor
wal -R &                               # set wallpaper and colors
setxkbmap br -option caps:swapescape & # change esc by capslock
redshift &                             # screen color temperature
dunst &                                # notifications daemon
xsetroot -cursor_name left_ptr &       # set cursor type
unclutter &                            # hide mouse
ibus-daemon -rxR &
anki &                                 # srs flashcards

exec bspwm                             # window manager
