local options = {
	context_commentstring = { enable = true },
	context = { enable = true },
	fold = { enable = true },
	indent = { enable = true },
	highlight = { enable = true, use_languagetree = true },
	ensure_installed = {
		"lua",
		"c",
		"make",
		"qmljs",
		"qmldir",
		"html",
		"rasi",
		"css",
		"scss",
		"diff",
		"sql",
		"json",
		"javascript",
		"tsx",
		"typescript",
		"bash",
		"python",
		"markdown_inline",
		"yaml",
		"vue",
		"vim",
	},
}

return options
